--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/MobPlugin
build-by-default: true
branches:
- main
- wip-mobs
projects:
  MobPlugin:
    path: ""
    lint:
      phpstan: false
...
